name: ci

on:
  workflow_dispatch:
    inputs:
      enable:
        description: "启用或禁用自动 GitHub 自动全绿功能"
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
  push:
    branches:
      - master
  schedule:
    - cron: "*/15 * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Auto green
        run: |
          set -e
          # 只有 schedule 触发时，随机概率执行，避免风控
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
           num=$(( RANDOM % 4 ))
            if [[ $num != 0 ]]; then
              echo "本次 schedule 触发不执行"
              exit 0
            fi
          fi

          git config --local user.email "${{ secrets.EMAIL }}"
          git config --local user.name "${{ secrets.NAME }}"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git pull --rebase
          commit_message="Keep writing documents at $(date +'%Y-%m-%d %H:%M:%S')"
          git commit --allow-empty -m "$commit_message"
          git push
